[target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb -q -x openocd.gdb"
# rustflags = ["-C", "link-arg=-Tlink.x"]
runner = "probe-rs run --chip STM32F303VC"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
